In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0.dev20230205


# Introduction to Tensors
## Creating Tensors

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX =torch.tensor([ [7,8],
                     [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [22]:
# TENSOR

TENSOR= torch.tensor([
    [
        [1,2,3],
        [3,6,9],
        [4,5,6]
    ],
    [
        [3,4,5],
        [6,7,8],
        [8,8,8]
    ]
])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [4, 5, 6]],

        [[3, 4, 5],
         [6, 7, 8],
         [8, 8, 8]]])

In [23]:
TENSOR.shape

torch.Size([2, 3, 3])

In [24]:
TENSOR.ndim

3

In [25]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [4, 5, 6]])

In [26]:
TENSOR[0][0]

tensor([1, 2, 3])

In [27]:
TENSOR[0][0][0]

tensor(1)

### Random Tensors
Why random tensors?
Random tensors are improtant because the way many nerwroks learn is that they start with tensors full of random numbers and then adjust those random numbers to better representthe data.

https://pytorch.org/docs/stable/generated/torch.rand.html

In [28]:
# Create a random tenrso of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7538, 0.0587, 0.2542, 0.7565],
        [0.1150, 0.3351, 0.2585, 0.8467],
        [0.2355, 0.7010, 0.8649, 0.5830]])

In [29]:
random_tensor.ndim

2

In [30]:
random_tensor.shape

torch.Size([3, 4])

In [32]:
## Create arandom tensor with similar shape of an image
random_image_tensor = torch.rand(size=(244,244,3)) # Wisth, Height, Color channels
random_image_tensor.ndim

3